/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as InvoicesInvoiceIdRouteImport } from './routes/invoices.$invoiceId'
import { Route as ApiPublicExtractInvoiceRouteImport } from './routes/api/public/extract-invoice'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesInvoiceIdRoute = InvoicesInvoiceIdRouteImport.update({
  id: '/invoices/$invoiceId',
  path: '/invoices/$invoiceId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicExtractInvoiceRoute = ApiPublicExtractInvoiceRouteImport.update({
  id: '/api/public/extract-invoice',
  path: '/api/public/extract-invoice',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/review': typeof ReviewRoute
  '/upload': typeof UploadRoute
  '/invoices/$invoiceId': typeof InvoicesInvoiceIdRoute
  '/api/public/extract-invoice': typeof ApiPublicExtractInvoiceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/review': typeof ReviewRoute
  '/upload': typeof UploadRoute
  '/invoices/$invoiceId': typeof InvoicesInvoiceIdRoute
  '/api/public/extract-invoice': typeof ApiPublicExtractInvoiceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/review': typeof ReviewRoute
  '/upload': typeof UploadRoute
  '/invoices/$invoiceId': typeof InvoicesInvoiceIdRoute
  '/api/public/extract-invoice': typeof ApiPublicExtractInvoiceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/history'
    | '/review'
    | '/upload'
    | '/invoices/$invoiceId'
    | '/api/public/extract-invoice'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/history'
    | '/review'
    | '/upload'
    | '/invoices/$invoiceId'
    | '/api/public/extract-invoice'
  id:
    | '__root__'
    | '/'
    | '/history'
    | '/review'
    | '/upload'
    | '/invoices/$invoiceId'
    | '/api/public/extract-invoice'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoryRoute: typeof HistoryRoute
  ReviewRoute: typeof ReviewRoute
  UploadRoute: typeof UploadRoute
  InvoicesInvoiceIdRoute: typeof InvoicesInvoiceIdRoute
  ApiPublicExtractInvoiceRoute: typeof ApiPublicExtractInvoiceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/$invoiceId': {
      id: '/invoices/$invoiceId'
      path: '/invoices/$invoiceId'
      fullPath: '/invoices/$invoiceId'
      preLoaderRoute: typeof InvoicesInvoiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/extract-invoice': {
      id: '/api/public/extract-invoice'
      path: '/api/public/extract-invoice'
      fullPath: '/api/public/extract-invoice'
      preLoaderRoute: typeof ApiPublicExtractInvoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoryRoute: HistoryRoute,
  ReviewRoute: ReviewRoute,
  UploadRoute: UploadRoute,
  InvoicesInvoiceIdRoute: InvoicesInvoiceIdRoute,
  ApiPublicExtractInvoiceRoute: ApiPublicExtractInvoiceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
